In [19]:
import csv
import numpy as np
import pandas as pd



In [26]:

df = pd.read_csv('walking_dataset1.csv',sep=None)



/home/niranjan/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support sep=None with delim_whitespace=False; you can avoid this warning by specifying engine='python'.
  from ipykernel import kernelapp as app


In [71]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])
print(a.shape)
print(a)
print(b.shape)
np.hstack((a,b))


(3, 1)
[[1]
 [2]
 [3]]
(3, 1)


array([[1, 2],
       [2, 3],
       [3, 4]])

In [47]:
a=np.array([1,2,3])
np.append(a, [4, 5, 6], axis=0)

array([1, 2, 3, 4, 5, 6])

In [60]:
a=np.append(1,2)

b=np.append(a,3)
a=np.append(a,4)
#print (a)
#print (b)
np.append(a,b,axis=1)

[1 2 4]
[1 2 3]


IndexError: axis 1 out of bounds [0, 1)

In [61]:
t1 = np.arange(1,10)

t2 = np.arange(11,20)
print(t1)
print(t2)

[1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


In [88]:

from numpy import genfromtxt
walking = genfromtxt('walking_dataset1.csv', delimiter=',')
standing=genfromtxt('standing_dataset1.csv', delimiter=',')
print(walking.shape)
print(standing.shape)


wl=np.ones((len(walking),1))


sl=np.zeros((len(walking),1))

data=np.vstack((walking[:,1:-1],standing[:,1:-1]))
print(data.shape)
labels=np.vstack((wl,sl))
print(labels.shape)




(480, 7)
(480, 7)
(960, 5)
(960, 1)


In [91]:
from sklearn import svm
clf = svm.SVC()
clf.fit(data, labels)  

/home/niranjan/anaconda3/lib/python3.5/site-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [106]:

walking2 = genfromtxt('walking_dataset2.csv', delimiter=',')
walking_accuracy=np.sum(clf.predict(walking2[:,1:-1]))/len(walking2)
print('walking_accuracy=',walking_accuracy*100)

walking_accuracy= 99.375


In [107]:
standing2 = genfromtxt('standing_dataset2.csv', delimiter=',')
standing_accuaracy=1-np.sum(clf.predict(standing2[:,1:-1]))/len(standing2)
print('standing_accuracy=',standing_accuaracy*100)

standing_accuracy= 88.3333333333
